#!/bin/bash

rm -rf "/tmp/double_redirects"
mkdir "/tmp/double_redirects"
#wget "http://localhost/wiki/index.php?title=Special:DoubleRedirects&limit=500&offset=0" -O /tmp/double_redirects.html
#lynx -dump "http://localhost/wiki/index.php?title=Special:DoubleRedirects&limit=500&offset=0" > /tmp/double_redirects.html
lynx -dump "http://localhost/wiki/index.php?title=Special:DoubleRedirects&limit=500&offset=0" | grep 'http://localhost/wiki/index.php?title=SC' | sed 's/^ *[0-9]*\. http:\/\/localhost\/wiki\/index\.php?title=//' | sed 's/&redirect=no.*//' | sort | uniq > "/tmp/double_redirects/remove_urls"
cat "/tmp/double_redirects/remove_urls" | grep "^SC:" | sed s/^SC:// > "/tmp/double_redirects/remove_ids"
find /media/share/Documentation/cfalcas/q/import_docs/work/ -type d | grep -f "/tmp/double_redirects/remove_ids" | sed s/^/rm\ -rf\ \"/ | sed s/$/\"/ > "/tmp/double_redirects/remove_localdirs"

# echo URLS:
# cat "/tmp/double_redirects/remove_urls"
# echo DIRS
# cat "/tmp/double_redirects/remove_localdirs"

php /var/www/html/wiki/maintenance/deleteBatch.php "/tmp/double_redirects/remove_urls"
bash "/tmp/double_redirects/remove_localdirs"
