<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );
require_once( "MediaWiki/StubManager/StubManager.php");

require_once("$IP/extensions/UsabilityInitiative/WikiEditor/WikiEditor.php");
require_once("$IP/extensions/UsabilityInitiative/Vector/Vector.php");
$wgVectorUseSimpleSearch = true;
$wgVectorUseIconWatch = true;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;  // Default user preference to use toolbar dialogs
$wgWikiEditorModules['toolbar']['global'] = true;  // Enable the WikiEditor toolbar for everyone
$wgWikiEditorModules['toolbar']['user'] = false;  // Don't allow users to turn the WikiEditor toolbar on/off individually
#$wgEnableMWSuggest = true;
#$wgDisableSearchContext = false;
#$wgAdvancedSearchHighlighting = true;
#$wgUseTwoButtonsSearchForm = false;

require_once( "MediaWiki/geshi/geshi.php");
#require_once( "extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");
#$wgSyntaxHighlightDefaultLang = "c";
#$geshi->enable_line_numbers(GESHI_FANCY_LINE_NUMBERS);
#$geshi->set_line_style('background: red;', 'background: blue;', true);

$wgUrlProtocols[] = "file:";
require_once( "extensions/syntax-highlighter-code-colorizer/syntax-highlighter-mediawiki.php");
#$wgSearchType = 'SphinxSearch';
#$wgSphinxSuggestMode = true;
#require_once( "$IP/extensions/SphinxSearch/SphinxSearch.php" );
## sphinx is disabled. To enable:
## chkconfig searchd on
## also in crontab, reenable index
require_once("$IP/extensions/FCKeditor/FCKeditor.php");
require_once( "$IP/extensions/APC/APC.php");
require_once("$IP/extensions/Cite/Cite.php");
$wgGroupPermissions['sysop']['DeleteOldRevisions'] = true;
#require_once( "$IP/extensions/SpecialDeleteOldRevisions2/SpecialDeleteOldRevisions2.php");

#require_once("{$IP}/extensions/CategoryTree/CategoryTree.php");
require_once( "$IP/extensions/LdapAuthentication/LdapAuthentication.php" );
$wgAuth = new LdapAuthenticationPlugin();
$wgLDAPUseLocal = true;

$wgLDAPDomainNames = array(
  "rom_domain"
);

$wgLDAPServerNames = array(
 "rom_domain"=>"romania2003.mindsoft.com"
);

$wgLDAPEncryptionType = array(
  "rom_domain"=>"clear"
);
$wgLDAPSearchStrings = array(
  "rom_domain"=>"rom_domain\\USER-NAME"
);
$wgLDAPBaseDNs = array(
  "rom_domain"=>"dc=mindcti,dc=com"
);

#$wgPasswordAttemptThrottle=0;
#$wgLDAPDebug = 3;
#$wgDebugLogGroups["ldap"] = "/tmp/debug.log" ;
//$wgLDAPOptions = array(
// "testADdomain"=>array( LDAP_OPT_DEREF, 0 ),
// "testLDAPdomain"=>array( LDAP_OPT_DEREF, 1 ),
//);

#$wgLDAPPort = array(
#  "rom_domain"=>443,
#  "testLDAPdomain"=>1636
#);
$wgSearchType = 'LuceneSearch';
#$wgLuceneHost = 'localhost';
$wgLuceneHost = '10.0.0.99';
$wgLucenePort = 8123;
require_once("extensions/MWSearch/MWSearch.php");
$wgLuceneSearchVersion = 2.1;

#$wgDebugLogFile = "/tmp/wiki_log.log";

$wgUseAjax = true;
$wgGroupPermissions['*']['createaccount'] = false;
#/usr/share/pear/MediaWiki/geshi/

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "WikiBrainzz";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/wiki";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO
#$wgCompressRevisions = true;

$wgEmergencyContact = "root@localhost";
$wgPasswordSender = "root@localhost";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wikidb";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "!0wikiuser@9";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
#$wgMainCacheType = CACHE_NONE;
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = false;
$wgExternalLinkTarget = '_blank';
# $wgUseImageMagick = true;
# $wgImageMagickConvertCommand = "/usr/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
# $wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = false;

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "e838863ffed0d6ffe6857a6421dce767904b92b6f80ae50cee07d4fcc619be07";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'vector';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "/usr/bin/diff3";

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );
#$wgLogo = "/wiki/MindControls.gif";
#$wgLogo = "/wiki/MindBenders.jpg";
#$wgLogo = "/wiki/logos/worker.jpg";
$wgLogo = "/wiki/logos/blue_red_pill3.jpg";
$wgEnableUploads = true;
#$wgAllowUserJs=true;
#$wgAllowUserCss=true;
$wgEnableAPI=true;

$wgCategoryPagingLimit = 600;

$wgFileExtensions = array_merge($wgFileExtensions, array('doc', 'xls', 'pdf', 'zip', 'xml', 'swf', 'zip'));
#$wgShowExceptionDetails = true;

$wgExtraNamespaces[100] = "SC";
$wgExtraNamespaces[110] = "SC_iPhonex_Bug";
$wgExtraNamespaces[120] = "SC_SIP_Bug";
$wgExtraNamespaces[130] = "SC_Sentori_Bug";
$wgExtraNamespaces[140] = "SC_Infrastructure_Bug";
$wgExtraNamespaces[150] = "SC_PaymentManager_Bug";
$wgExtraNamespaces[160] = "SC_PhonexONE_Bug";
$wgExtraNamespaces[170] = "SC_Nagios_Bug";
$wgExtraNamespaces[115] = "SC_iPhonex_Change";
$wgExtraNamespaces[125] = "SC_SIP_Change";
$wgExtraNamespaces[135] = "SC_Sentori_Change";
$wgExtraNamespaces[145] = "SC_Infrastructure_Change";
$wgExtraNamespaces[155] = "SC_PaymentManager_Change";
$wgExtraNamespaces[165] = "SC_PhonexONE_Change";
$wgExtraNamespaces[175] = "SC_Nagios_Change";
$wgExtraNamespaces[199] = "SC_Canceled";
$wgExtraNamespaces[200] = "CRM";
$wgExtraNamespaces[300] = "CMS";
$wgExtraNamespaces[400] = "SVN";
$wgExtraNamespaces[500] = "CRM_iPhonex";
$wgExtraNamespaces[600] = "CRM_PhonexONE";
$wgExtraNamespaces[700] = "CRM_Sentori";
$wgExtraNamespaces[900] = "Test";
$wgExtraNamespaces[1000] = "RN";

$wgNamespacesToBeSearchedDefault = array(
	NS_MAIN =>           true,
	NS_TALK =>           false,
	NS_USER =>           false,
	NS_USER_TALK =>      false,
	NS_PROJECT =>        false,
	NS_PROJECT_TALK =>   false,
	NS_IMAGE =>          false,
	NS_IMAGE_TALK =>     false,
	NS_MEDIAWIKI =>      false,
	NS_MEDIAWIKI_TALK => false,
	NS_TEMPLATE =>       false,
	NS_TEMPLATE_TALK =>  false,
	NS_HELP =>           false,
	NS_HELP_TALK =>      false,
	NS_CATEGORY =>       false,
	NS_CATEGORY_TALK =>  false,
	100		=>   true,
	110		=>   true,
	115		=>   true,
	120		=>   true,
	125		=>   true,
	130		=>   true,
	135		=>   true,
	140		=>   true,
	145		=>   true,
	150		=>   true,
	155		=>   true,
	160		=>   true,
	165		=>   true,
	170		=>   true,
	175		=>   true,
	199		=>   false,
	300		=>   true,
	400		=>   true,
	200		=>   true,
	500		=>   true,
	600		=>   true,
	700		=>   true,
	1000		=>   true
);

