<?php
# This file was automatically generated by the MediaWiki 1.21alpha
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}
#$wgReadOnly = 'This wiki is readonly due to AIDS.';

#error_reporting(E_ALL);
#ini_set("display_errors", 1);
#$wgShowSQLErrors = true;
#$wgDebugDumpSql  = true;
#$wgDebugLogFile = "/var/log/wiki_log.log";
#$wgShowExceptionDetails = true;
#$wgLDAPDebug = 3;

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

#$wgReadOnly = "We are upgrading MediaWiki, please be patient. This wiki will be back in a few hours.";
#$wgReadOnlyFile="/var/www/html/wiki/RO_reason.txt";
$wgGroupPermissions['sysop']['DeleteOldRevisions'] = true;
#$wgDirectoryMode = 775;

require_once( "$IP/includes/DefaultSettings.php" );
require_once( "$IP/extensions_git/Vector/Vector.php" );
require_once( "$IP/extensions_git/WikiEditor/WikiEditor.php" );
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;  // Default user preference to use toolbar dialogs
$wgDefaultUserOptions['useeditwarning'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;
$wgWikiEditorModules['toolbar']['global'] = 1;  // Enable the WikiEditor toolbar for everyone
$wgWikiEditorModules['toolbar']['user'] = 0;  // Don't allow users to turn the WikiEditor toolbar on/off individually
#$wgVectorFeatures['collapsiblenav']['global'] = true;
#$wgVectorFeatures['expandablesearch']['global'] = true;
#$wgVectorUseSimpleSearch = true;
#$wgVectorUseIconWatch = true;
#$wgVectorFeatures['expandablesearch']['global'] = 1;
#$wgVectorFeatures['editwarning']['global'] = true;

$wgVectorFeatures = array(
    'collapsiblenav' => array( 'global' => true, 'user' => true ),
    'collapsibletabs' => array( 'global' => true, 'user' => false ),
    'editwarning' => array( 'global' => false, 'user' => true ),
    'simplesearch' => array( 'global' => true, 'user' => true ),
    // The follwing are experimental and likely unstable - use at your own risk
    'expandablesearch' => array( 'global' => false, 'user' => false ),
    'footercleanup' => array( 'global' => false, 'user' => false ),
 'sectioneditlinks' => array( 'global' => false, 'user' => false ),
);
#$wgCollapsibleNavBucketTest = 1;
// Force the new version
#$wgCollapsibleNavForceNewVersion = 1;
require_once( "$IP/extensions_git/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");
$wgSyntaxHighlightDefaultLang = "c";

$wgUrlProtocols[] = "file:";
require_once( "$IP/extensions_mind/SyntaxHighlighter/syntax-highlighter-mediawiki.php");
require_once( "$IP/extensions_mind/Flash.php" );
require_once( "$IP/extensions_mind/ToggleDisplay/ToggleDisplay.php" );
require_once( "$IP/extensions_mind/DeploymentConsideration/DeploymentConsideration.php" );
#require_once( "$IP/extensions_git/APC/APC.php");
#$wgGroupPermissions['*']['apc'] = true;
require_once( "$IP/extensions_git/Cite/Cite.php");

require_once( "$IP/extensions_git/LdapAuthentication/LdapAuthentication.php" );
$wgAuth = new LdapAuthenticationPlugin();
$wgLDAPUseLocal = true;
$wgLDAPDomainNames = array( "rom_domain", "mind_dom");
$wgLDAPServerNames = array( "rom_domain"=>"romania2003.mindsoft.com", "mind_dom"=>"mail.mindcti.com");
$wgLDAPEncryptionType = array( "rom_domain"=>"clear", "mind_dom"=>"clear");
$wgLDAPSearchStrings = array( "rom_domain"=>"rom_domain\\USER-NAME", "mind_dom"=>"mind_dom\\USER-NAME");
$wgLDAPBaseDNs = array( "rom_domain"=>"dc=mindcti,dc=com", "mind_dom"=>"dc=mindcti,dc=com");
$wgAutoblockExpiry = "3";

$wgSearchType = 'LuceneSearch';
#$wgLuceneHost = '10.0.0.99';
$wgLuceneHost = 'wikitiki.mindsoft.com';
$wgLucenePort = 8123;

require_once("$IP/extensions_mind/MWSearch/MWSearch.php");
$wgLuceneSearchVersion = 2.1;

require_once( "$IP/extensions_mind/NewestPages/NewestPages.php" );

$wgUseAjax = true;
$wgGroupPermissions['*']['createaccount'] = false;

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename      = "Wiki Brainzzz";
$wgMetaNamespace = "Wiki_Brainzzz";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/wiki";
$wgScriptExtension  = ".php";

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://wikitiki.mindsoft.com";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
## $wgLogo             = "$wgStylePath/common/images/wiki.png";
$wgLogo = "/wiki/logos/marvin.jpg";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO
$wgCompressRevisions = true;

$wgEmergencyContact = "cristian.falcas@mindcti.com";
$wgPasswordSender   = "cristian.falcas@mindcti.com";

$wgEnotifUserTalk      = true; # UPO
$wgEnotifWatchlist     = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "wikidb";
$wgDBuser           = "wikiuser";
$wgDBpassword       = "!0wikiuser@9";

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType    = CACHE_ACCEL;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgExternalLinkTarget = '_blank';

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "en";

$wgSecretKey = "30398fb900c5a3b7ab167bde29d9b72b994399ac4151ade00cfdf3ac29ed7459";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "e1438e9b1f2c5c0d";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# End of automatically generated settings.
# Add more configuration options below.

$wgInvalidateCacheOnLocalSettingsChange = true;
$wgEnableAPI = true;
$wgCategoryPagingLimit = 600;
$wgMaxArticleSize = 20480;

$wgFileExtensions = array_merge($wgFileExtensions, 
    array('doc', 'xls', 'pdf', 'zip', 'xml', 'swf', 'bat', 'mp4'));
$wgFileBlacklist = array_diff( $wgFileBlacklist, $wgFileExtensions );
$wgShowExceptionDetails = true;

##even numbers are the new namspaces, odd numbers are the DISCUSSION namespaces
## don't use odd numbers
$wgExtraNamespaces[100] = "SC";
$wgExtraNamespaces[200] = "SC_Deployment";
$wgExtraNamespaces[300] = "SC_iPhonex_Bug";
$wgExtraNamespaces[400] = "SC_iPhonex_Change";
$wgExtraNamespaces[500] = "SC_Sentori_Bug";
$wgExtraNamespaces[600] = "SC_Sentori_Change";
$wgExtraNamespaces[700] = "SC_PaymentManager_Bug";
$wgExtraNamespaces[800] = "SC_PaymentManager_Change";
$wgExtraNamespaces[900] = "SC_SIP_Bug";
$wgExtraNamespaces[1000] = "SC_SIP_Change";
$wgExtraNamespaces[1100] = "SC_Nagios_Bug";
$wgExtraNamespaces[1200] = "SC_Nagios_Change";
$wgExtraNamespaces[1300] = "SC_Infrastructure_Bug";
$wgExtraNamespaces[1400] = "SC_Infrastructure_Change";
$wgExtraNamespaces[1500] = "SC_Abacus_Bug";
$wgExtraNamespaces[1600] = "SC_Abacus_Change";
$wgExtraNamespaces[1700] = "SC_PhonexONE_Bug";
$wgExtraNamespaces[1800] = "SC_PhonexONE_Change";
$wgExtraNamespaces[1900] = "SC_PhonEX_Bug";
$wgExtraNamespaces[2000] = "SC_PhonEX_Change";
$wgExtraNamespaces[2100] = "SC_Plugins_Bug";
$wgExtraNamespaces[2200] = "SC_Plugins_Change";
$wgExtraNamespaces[2300] = "SC_CMS_Bug";
$wgExtraNamespaces[2400] = "SC_CMS_Change";
$wgExtraNamespaces[2500] = "SC_MindReporter_Bug";
$wgExtraNamespaces[2600] = "SC_MindReporter_Change";
$wgExtraNamespaces[2700] = "SC_Simulators_Bug";
$wgExtraNamespaces[2800] = "SC_Simulators_Change";
$wgExtraNamespaces[2900] = "SC_Other_Bug";
$wgExtraNamespaces[3000] = "SC_Other_Change";
$wgExtraNamespaces[3100] = "SC_Canceled";
$wgExtraNamespaces[5000] = "CRM";
$wgExtraNamespaces[5100] = "CRM_iPhonex";
$wgExtraNamespaces[5200] = "CRM_PhonexONE";
$wgExtraNamespaces[5300] = "CRM_Sentori";
$wgExtraNamespaces[5400] = "SVN";
$wgExtraNamespaces[5500] = "CMS";
$wgExtraNamespaces[5600] = "SVN_SC";
$wgExtraNamespaces[5700] = "RN";
$wgExtraNamespaces[9000] = "Test";

$wgNamespacesToBeSearchedDefault = array(
	NS_MAIN =>           true,
	NS_TALK =>           false,
	NS_USER =>           false,
	NS_USER_TALK =>      false,
	NS_PROJECT =>        false,
	NS_PROJECT_TALK =>   false,
	NS_IMAGE =>          false,
	NS_IMAGE_TALK =>     false,
	NS_MEDIAWIKI =>      false,
	NS_MEDIAWIKI_TALK => false,
	NS_TEMPLATE =>       false,
	NS_TEMPLATE_TALK =>  false,
	NS_HELP =>           false,
	NS_HELP_TALK =>      false,
	NS_CATEGORY =>       false,
	NS_CATEGORY_TALK =>  false,
	100		=>   true,
	200		=>   true,
	300		=>   true,
	400		=>   true,
	500		=>   true,
	600		=>   true,
	700		=>   true,
	800		=>   true,
	900		=>   true,
	1000		=>   true,
	1100		=>   true,
	1200		=>   true,
	1300		=>   true,
	1400		=>   true,
	1500		=>   true,
	1600		=>   true,
	1700		=>   true,
	1800		=>   true,
	1900		=>   true,
	2000		=>   true,
	2100		=>   true,
	2200		=>   true,
	2300		=>   true,
	2400		=>   true,
	2500		=>   true,
	2600		=>   true,
	2700		=>   true,
	2800		=>   true,
	2900		=>   true,
	3000		=>   true,
	3100		=>   true,
	5000		=>   true,
	5100		=>   true,
	5200		=>   true,
	5300		=>   true,
	5400		=>   true,
	5500		=>   true,
	5600		=>   true,
	5700		=>   true,
	9000		=>   true,
);
